on:
  workflow_call:
    inputs:
      push-image:
        type: boolean
        required: true

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    if: success() && github.ref_name == github.event.repository.default_branch
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Log in to GitHub Container Registry
        if: inputs.push-image
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          push: ${{ inputs.push-image }}
          build-args: |
            APP_VERSION=${{ github.sha }}
          tags: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:${{ github.sha }}"
