on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      debian-version:
        required: false
        type: string
        default: bookworm

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/blindfoldedsurgery/poetry:1.1.1-pipx-${{ inputs.python-version }}-${{ inputs.debian-version }}
    steps:
      - uses: actions/checkout@v4
      - run: poetry install --all-extras
      - name: Check coding standards
        run: |
          poetry run ruff check src/
          poetry run black --check src/
          poetry run mypy src/
