on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      debian-version:
        required: false
        type: string
        default: bookworm

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:${{ inputs.python-version }}-slim-${{ inputs.debian-version }}
    steps:
      - name: Install Poetry
        run: pip install poetry==1.7.0
      - uses: actions/checkout@v4
      - run: poetry install --all-extras
      - name: Check coding standards
        run: |
          poetry run ruff check src/
          poetry run black --check src/
          poetry run mypy src/
