on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      debian-version:
        required: false
        type: string
        default: bookworm
      pypi-username:
        required: true
        type: string
      repo-name:
        required: false
        type: string
        default: pypi-bs
    secrets:
      pypi-password:
        required: true

jobs:
  publish-package:
    runs-on: ubuntu-latest
    container: ghcr.io/blindfoldedsurgery/poetry:1.1.1-pipx-${{ inputs.python-version }}-${{ inputs.debian-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: poetry build
      - name: Set credentials
        run: |
          poetry config "http-basic.${{ inputs.repo-name }}" \
          "${{ inputs.pypi-username }}" \
          "${{ secrets.pypi-password }}"
      - name: Upload to pypi registry
        run: poetry publish -r ${{ inputs.repo-name }}
