on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      debian-version:
        required: false
        type: string
        default: bookworm
      submit-coverage:
        required: false
        type: boolean
        default: false
      tests-location:
        required: false
        type: string
        default: src/
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:${{ inputs.python-version }}-slim-${{ inputs.debian-version }}
    steps:
      - name: Install Poetry
        run: pip install poetry==1.8.3
      - uses: actions/checkout@v4
      - run: poetry install --all-extras
      - name: Run tests
        if: '!inputs.submit-coverage'
        run: poetry run pytest
      - name: Run tests with coverage
        if: inputs.submit-coverage
        run: poetry run pytest --cov ${{ inputs.tests-location }}
      - name: Convert Python coverage file format to XML
        if: inputs.submit-coverage
        run: poetry run coverage xml
      - name: Store coverage artifact
        if: inputs.submit-coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: ./coverage.xml
          overwrite: true

  upload-coverage-report:
    runs-on: ubuntu-latest
    needs: [ test ]
    if: inputs.submit-coverage
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
